// Generated by CoffeeScript 1.3.3
(function() {

  this.App = Ember.Application.create();

  App.ApplicationView = Ember.View.extend({
    templateName: 'application'
  });

  App.ApplicationController = Ember.Controller.extend();

  App.AllContributorsController = Ember.ArrayController.extend();

  App.AllContributorsView = Ember.View.extend({
    templateName: 'contributors'
  });

  App.OneContributorController = Ember.ObjectController.extend();

  App.OneContributorView = Ember.View.extend({
    templateName: 'a-contributor'
  });

  App.DetailsView = Ember.View.extend({
    templateName: 'details'
  });

  App.ReposView = Ember.View.extend({
    templateName: 'repos'
  });

  App.Contributor = Ember.Object.extend({
    loadRepos: function() {
      return $.ajax({
        url: 'https://api.github.com/users/%@/repos'.fmt(this.get('login')),
        context: this,
        dataType: 'jsonp',
        success: function(resp) {
          return this.set('repos', resp.data);
        }
      });
    },
    loadMoreDetails: function() {
      return $.ajax({
        url: 'https://api.github.com/users/%@'.fmt(this.get('login')),
        context: this,
        dataType: 'jsonp',
        success: function(resp) {
          return this.setProperties(resp.data);
        }
      });
    }
  });

  App.Contributor.reopenClass({
    allContributors: [],
    notContributors: [],
    findOne: function(username) {
      var contributor;
      contributor = App.Contributor.create({
        login: username
      });
      $.ajax({
        url: 'https://api.github.com/repos/emberjs/ember.js/contributors',
        dataType: 'jsonp',
        context: contributor,
        success: function(resp) {
          return this.setProperties(resp.data.filterProperty('login', username));
        }
      });
      return contributor;
    },
    find: function() {
      var x;
      x = this;
      $.ajax({
        url: 'https://api.github.com/repos/emberjs/ember.js/contributors',
        dataType: 'jsonp',
        context: this,
        success: function(resp) {
          var c, os;
          os = (function() {
            var _i, _len, _ref, _results;
            _ref = resp.data;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              c = _ref[_i];
              _results.push(App.Contributor.create(c));
            }
            return _results;
          })();
          this.allContributors.addObjects(os);
          return this.notContributors.addObjects(resp.data);
        }
      });
      window.not_contribs = this.notContributors;
      window.contribs = this.allContributors;
      return this.allContributors;
    }
  });

  App.Router = Ember.Router.extend({
    enableLogging: true,
    root: Ember.Route.extend({
      contributors: Ember.Route.extend({
        route: '/',
        showContributor: Ember.Route.transitionTo('aContributor'),
        connectOutlets: function(router) {
          return router.get('applicationController').connectOutlet('allContributors', App.Contributor.find());
        }
      }),
      aContributor: Ember.Route.extend({
        route: '/:githubUserName',
        showAllContributors: Ember.Route.transitionTo('contributors'),
        showDetails: Ember.Router.transitionTo('details'),
        showRepos: Ember.Router.transitionTo('repos'),
        connectOutlets: function(router, context) {
          return router.get('applicationController').connectOutlet('oneContributor', context);
        },
        serialize: function(router, context) {
          return {
            githubUserName: context.login
          };
        },
        deserialize: function(router, urlParams) {
          return App.Contributor.findOne(urlParams.githubUserName);
        },
        initialState: 'details',
        details: Ember.Route.extend({
          route: '/',
          connectOutlets: function(router) {
            router.get('oneContributorController.content').loadMoreDetails();
            return router.get('oneContributorController').connectOutlet('details');
          }
        }),
        repos: Ember.Route.extend({
          route: '/repos',
          connectOutlets: function(router) {
            router.get('oneContributorController.content').loadRepos();
            return router.get('oneContributorController').connectOutlet('repos');
          }
        })
      })
    })
  });

  App.initialize();

}).call(this);
